class_name TexLib
## The surface library.
##
## Every material in the game comes from a texture set generated by
## tools/gen_textures.py.  Each set has an albedo, a tangent-space normal and a
## roughness map, plus a declared tile size in metres so a brick wall and a
## concrete wall show the same real-world scale regardless of how large the
## geometry they are applied to happens to be.
##
## All world materials use world-space triplanar projection.  That is the
## important detail: geometry here is assembled from boxes that get scaled and
## rotated arbitrarily, and triplanar means the texture can never stretch with
## the box.  It also lets a merged mesh carry five million triangles worth of
## uniform texel density for the cost of one extra fetch per axis.

const DIR := "res://assets/textures/"

static var _manifest: Dictionary = {}
static var _mats: Dictionary = {}


static func manifest() -> Dictionary:
	if _manifest.is_empty():
		var f := FileAccess.open(DIR + "manifest.json", FileAccess.READ)
		if f != null:
			var parsed = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				_manifest = parsed
		if _manifest.is_empty():
			push_warning("TexLib: manifest missing -- run tools/gen_textures.py")
	return _manifest


static func _tex(kind: String, name: String) -> Texture2D:
	return load("%s%s_%s.png" % [DIR, name, kind]) as Texture2D


## Build (and cache) a lit material from a generated texture set.
##
##   name   texture set, e.g. "concrete" / "wood" / "steel_rust"
##   tint   multiplies the albedo, which is how one steel set becomes a dozen
##          differently painted props
##   tile   overrides the set's own tile size, in metres
##   emit   emission colour; energy > 0 turns the surface into a light source
static func mat(name: String, tint := Color.WHITE, tile := -1.0,
		rough_scale := 1.0, emit := Color.BLACK, energy := 0.0,
		alpha := 1.0, use_normal := true) -> StandardMaterial3D:
	var key := "%s|%s|%.3f|%.2f|%s|%.2f|%.2f|%s" % [name, tint.to_html(true), tile,
			rough_scale, emit.to_html(true), energy, alpha, str(use_normal)]
	if _mats.has(key):
		return _mats[key]

	var entry: Dictionary = manifest().get(name, {})
	if entry.is_empty():
		push_warning("TexLib: unknown texture set '%s'" % name)
		entry = {"tile_m": 2.0, "metallic": 0.0}

	var m := StandardMaterial3D.new()
	m.albedo_texture = _tex("alb", name)
	m.albedo_color = tint
	m.metallic = float(entry.get("metallic", 0.0))
	m.metallic_specular = 0.45
	m.roughness = clampf(float(entry.get("roughness", 0.85)) * rough_scale, 0.03, 1.0)

	var rough_tex := _tex("rgh", name)
	if rough_tex != null:
		m.roughness_texture = rough_tex
		m.roughness_texture_channel = BaseMaterial3D.TEXTURE_CHANNEL_RED

	var nrm := _tex("nrm", name) if use_normal else null
	if nrm != null:
		m.normal_enabled = true
		m.normal_texture = nrm
		m.normal_scale = float(entry.get("normal_strength", 1.0))

	var t := tile if tile > 0.0 else float(entry.get("tile_m", 2.0))
	# world-space triplanar: uv1_scale is "tiles per metre" on world position
	m.uv1_triplanar = true
	m.uv1_scale = Vector3.ONE * (1.0 / maxf(t, 0.05))
	m.uv1_triplanar_sharpness = 4.0
	m.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC

	if alpha < 1.0:
		m.albedo_color.a = alpha
		m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		m.cull_mode = BaseMaterial3D.CULL_DISABLED
	if energy > 0.0:
		m.emission_enabled = true
		m.emission = emit if emit != Color.BLACK else tint
		m.emission_energy_multiplier = energy

	_mats[key] = m
	return m


## A flat, unshaded material for signage, decals and light shafts.
static func flat(color: Color, alpha := 1.0, additive := true) -> StandardMaterial3D:
	var key := "flat_%s_%.2f_%s" % [color.to_html(true), alpha, str(additive)]
	if _mats.has(key):
		return _mats[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = Color(color.r, color.g, color.b, alpha)
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	m.disable_receive_shadows = true
	if alpha < 1.0:
		m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	if additive:
		m.blend_mode = BaseMaterial3D.BLEND_MODE_ADD
	_mats[key] = m
	return m


## Glass with a reflection card so windows read as glazing rather than holes.
static func glass(tint := Color(0.36, 0.44, 0.47), alpha := 0.55) -> StandardMaterial3D:
	var key := "glass_%s_%.2f" % [tint.to_html(true), alpha]
	if _mats.has(key):
		return _mats[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = Color(tint.r, tint.g, tint.b, alpha)
	m.metallic = 0.85
	m.roughness = 0.12
	m.metallic_specular = 0.9
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	m.disable_receive_shadows = true
	_mats[key] = m
	return m


## Interior darkness behind a window or door opening.  Unshaded so it reads as
## depth rather than as a lit surface in shadow.
static func interior(darkness := 0.055) -> StandardMaterial3D:
	var key := "interior_%.3f" % darkness
	if _mats.has(key):
		return _mats[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = Color(darkness, darkness * 1.04, darkness * 1.12)
	m.roughness = 1.0
	m.disable_receive_shadows = true
	m.disable_ambient_light = true
	_mats[key] = m
	return m


## Grime decal, alpha-blended, used to sit staining at the foot of walls.
static func grunge() -> StandardMaterial3D:
	if _mats.has("grunge"):
		return _mats["grunge"]
	var m := StandardMaterial3D.new()
	m.albedo_texture = _tex("alb", "grunge")
	m.albedo_color = Color(1, 1, 1, 0.9)
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_DEPTH_PRE_PASS
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	m.roughness = 1.0
	m.uv1_scale = Vector3(0.25, 0.25, 0.25)
	_mats["grunge"] = m
	return m
